title = "Airspace for Hugo"
baseURL = ""
languageCode = "en-us"
theme = "airspace-hugo"
themeDir = "themes"

# The site's parameters
[params]
  home = "Home"

  [menu]

    [[menu.header]]
      weight = 2
      name = "GitHub"
      url = "https://github.com/rauniyars"
    [[menu.header]]
      weight = 3
      name = "LinkedIn"
      url = "https://www.linkedin.com/feed/"
    [[menu.header]]
      weight = 4
      name = "Facebook"
      url = "https://www.facebook.com/sweta.rauniyar"
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "contact"

    [[menu.footer]]
      weight = 1
      name = "About me"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact me"
      url = "contact"
    [[menu.footer]]
      weight = 3
      name = "How it works"
      url = "work"
    [[menu.footer]]
      weight = 4
      name = "Blog"
      url = "blog"
    [[menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"

  [params.slider]
    enable = true
    title = "Sweta Rauniyar"
    subtitle = "What you seek is seeking you.<br/>Aspiring Data Analyst."
    bgImage = "img/slider-bg1.jpg"
    btnText = "Discover My Recent Research"
    url = "https://github.com/rauniyars/CS480WebProjects"

  [params.wrapper]
    enable = true
    image = "img/wrapper-img.jpeg"
    title = "About Me"
    italic = "My name is Sweta Rauniyar. I am an international student at Allegheny College."
    paragraph = "I was born and raised in Nepal, a small country located in the lap of the Himalayas. I made my college journey miles away from home to the land of opportunities, the United States of America! I have always been amazed by codes and how it makes it possible for us to interact with computers. I have always been amazed by how computers work and that is how I ended up becoming a Computer Science major."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "The Computer Science Journey"
    bgImage = "img/feature-bg.jpg"
    content = "The Computer Science department at Allegheny has allowed me to take a variety of courses across the department. I have throughly enjoyed learning and implementing concepts in the field of Data Analytics and that is what I've decided to focus my career in."
    [params.feature.button]
      caption = "View Works"
      url = "https://github.com/rauniyars"


  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Discover CS at Allegheny"
    paragraph = "Learn more about what Allegheny College has to offer in terms of Computer Science. Come find your unique combination."
    [params.call.button]
      url = "https://www.cs.allegheny.edu"
      text = "find your story"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
